import type { Metadata } from "next";
import "./styles/globals.css";
import { ReactNode } from "react";
import { Merriweather } from "next/font/google";
import { Header, SidebarNav } from "@/widgets";
import { SidebarProvider } from "@/shared/ui/sidebar";
import { cookies } from "next/headers";

const EXPANDED_SIDEBAR_WIDTH = 220;
const COLLAPSED_SIDEBAR_WIDTH = 77;

const merriweather = Merriweather({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" className={merriweather.variable}>
      <body>
        <Header />
        <SidebarProvider
          defaultOpen={defaultOpen}
          style={
            {
              "--sidebar-width": `${EXPANDED_SIDEBAR_WIDTH}px`,
              "--sidebar-width-icon": `${COLLAPSED_SIDEBAR_WIDTH}px`,
            } as React.CSSProperties
          }
        >
          <div className="flex w-full">
            <SidebarNav />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
