import type { Metadata } from "next";
import "./styles/globals.css";
import { ReactNode } from "react";
import { Merriweather } from "next/font/google";
import { Header } from "@/widgets";

const merriweather = Merriweather({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={merriweather.variable}>
      <body>
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
