export { HomeHero } from "./ui/HomeHero";
export { HomeTechnologies } from "./ui/HomeTechnologies";
export { HomeAboutProject } from "./ui/HomeAboutProject";
export { HomeStats } from "./ui/HomeStats";
export { HomeCTA } from "./ui/HomeCTA";
export { CTA_BUTTONS_DATA, type ICTAButtonData } from "./model/ctaData";
export { CTAButton } from "./ui/CTAButton";
export { STATS_DATA, type IStatsData } from "./model/statsData";
export { StatsCard } from "./ui/StatsCard";
export { AnimatedHeroText } from "./ui/AnimatedHeroText";
