import type { Metadata } from "next";
import "@/app/styles/globals.css";
import { CSSProperties, ReactNode } from "react";
import { SidebarNav, Header, LayoutStar } from "@/widgets";
import { SidebarProvider } from "@/shared/ui/sidebar";
import { cookies } from "next/headers";
import { EXPANDED_SIDEBAR_WIDTH, COLLAPSED_SIDEBAR_WIDTH } from "@/shared/constants";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  const messages = await getMessages();
  const locale = (await params).locale;

  return (
    <html lang={locale} className={inter.variable}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />

          <SidebarProvider
            defaultOpen={defaultOpen}
            style={
              {
                "--sidebar-width": `${EXPANDED_SIDEBAR_WIDTH}px`,
                "--sidebar-width-icon": `${COLLAPSED_SIDEBAR_WIDTH}px`,
              } as CSSProperties
            }
          >
            <div className="flex w-full">
              <SidebarNav />

              <LayoutStar>{children}</LayoutStar>
            </div>
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
